apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: daniel-lopez-fisag-dev
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: danielopezh/comments-frontend:{{ tag }}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: daniel-lopez-fisag-dev
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: daniel-lopez-fisag-dev
  labels:
    app: frontend
spec:
  host: frontend-daniel-lopez-fisag-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 80
